### ISSUE TITLE
How to always start from 0

### ISSUE THREAD

**Issue by dixhuit** [Leocardoso94/animated-number-vue#50]
`<animated-number/>` seems to always start counting from 0 OR the last value it counted to - this makes sense for many use cases. My use case requires that I always start counting from 0. I'm using `<animated-number/>` within a component that is loaded on each page, with a different value per page. Each page is not concerned with the previous page's value and should start counting from 0.

Any advice would be very welcome :)

**Comment by seifsay3d-zz** [comment]
Hi @danbohea, it would be easier to debug if you show your code. But I'm guessing maybe it's related to the duration you set? try removing it if you have a duration set.

**Comment by dixhuit** [comment]
Thanks for responding but I've fixed this now; I wasn't forcing a fresh instance of my component to be built each time (fixed by adding a `:key` to my `router-view` that was loading the component in question).
