### ISSUE TITLE
Allow rounding

### ISSUE THREAD

**Issue by OmgImAlexis** [Leocardoso94/animated-number-vue#7]
Is there currently any way to enable the `round` feature of `animejs`?

For example https://www.npmjs.com/package/animejs#dom-attributes
```
anime({
  targets: input,
  value: 1000 // Animate the input value to 1000
  round: 1 // Remove decimals by rounding the value
});
```

**Comment by Leocardoso94** [comment]
sorry for the delay in responding. 

I'll take a look at this attribute, thank you. 
But for now you can use the formatValue prop to do this
