### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by liangmc89** [Leocardoso94/animated-number-vue#8]
The value bound with this component does not match the actual value
``<div class="row">
                <div class="col">
                  <div class="overview-quantity">
                    {{guide.work}}
                    <animated-number class='text-pl' key="yzs_work" :formatValue="format" :value="guide.work" :duration="600" />
                  </div>
                  <div class="overview-footer">带团</div>
                </div>
                <div class="col">
                  <div class="overview-quantity">
                    {{guide.mountGuard}}
                    <animated-number class='text-rl' key='yzs_mountGuard' :formatValue="format" :value="guide.mountGuard" :duration="600" />
                  </div>
                  <div class="overview-footer">在岗</div>
                </div>
                <div class="col">
                  <div class="overview-quantity">
                    {{guide.all}}
                    <animated-number class='text-pl' key="yzs_all" :formatValue="format" :value="guide.all" :duration="600" />
                  </div>
                  <div class="overview-footer">全部</div>
                </div>
              </div>``
![1](https://user-images.githubusercontent.com/17973427/50063130-e1dce700-01e5-11e9-9011-8b9377f4eb96.png) 
 the font of white is actual value and the other color is use the component

**Comment by Leocardoso94** [comment]
what is the value of the formatValue prop?
